name:                release-bot
version:             0.1.0.0
github:              "githubuser/release-bot"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/release-bot#readme>

dependencies:
- base >= 4.9 && < 5
- aeson
- http-api-data
- http-client-tls
- mtl
- servant
- servant-client
- servant-server
- text
- wai-extra
- warp

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror

executables:
  release-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - release-bot

tests:
  release-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - release-bot
